<?xml version="1.0"?>

<package format="3">
  <name>steering_angle_plugin</name>
  <version>0.0.1</version>
  <description>Publish average steering angle from front joints.</description>

  <maintainer email="dongmin@example.com">Dongmin</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>gazebo_dev</depend>
  <depend>gazebo_ros</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
